version: "2.2"
services:
  pyassess-dashboard:
    image: geoapos/pyassess_raise
    container_name: pyassess-dashboard
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db-pyassess:5432/test_db
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=30a301d7257
    ports:
        - '8091:8080'
  db-pyassess:
    image: postgres:14.7
    container_name: db-pyassess
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 30a301d7257
      POSTGRES_DB: test_db
  code-inspector-dashboard:
    image: archontisk/codeinspector
    container_name: code-inspector-dashboard
    depends_on:
      db-code-inspector:
          condition: service_healthy
    environment:
        - DB_URL=mysql+pymysql://root:root@195.251.210.147:3366/code_inspector_db
    ports:
        - '8092:8000'
  db-code-inspector:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code_inspector_db
      MYSQL_PASSWORD: root
    ports:
      - '3366:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3